version = 0.1
[default]
[default.build]
# No parameters needed for a simple build.
[default.build.parameters]
# No parameters required, but section must exist.

[default.deploy]
# No parameters needed for local development.
[default.deploy.parameters]
# No parameters required, but section must exist.

[default.local_s3]
# No parameters needed for this use case.

[default.local_lambda]
# Parameters for running Lambda locally.
[default.local_lambda.parameters]
environment = """
{
  "CLIENT_ID": "your_dev_client_id",
  "CLIENT_SECRET": "your_dev_client_secret",
  "API_KEY": "your_dev_api_key",
  "REDIRECT_URI": "http://127.0.0.1:3000/default/BungieOAuthHandoff"
}
"""

[default.local_api]
# Parameters for running the API Gateway locally.
[default.local_api.parameters]
port = 3000
host = "127.0.0.1"